name: Andrea Cardaci
email: cyrus.and@gmail.com

permalink: pretty

collections:
  - advisories

defaults:
  - values:
      layout: "post"

exclude: ["/Gemfile", "/Makefile", "/README.md", "/CNAME"]

kramdown:
  parse_block_html: true
