title: Andrea Cardaci
description: Personal website
email: cyrus.and@gmail.com

permalink: pretty

defaults:
  - values:
      layout: "post"

exclude: ["/Gemfile", "/Makefile", "/README.md", "/CNAME"]

kramdown:
  parse_block_html: true

plugins:
  - jekyll-feed
